services:
  - type: web
    name: solana-cleanup-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: YOUR_BOT_TOKEN_HERE
